services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: bidmart_catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${MY_SECRET_DB_PASS:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 128M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bidmart_catalog"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=${SERVER_PORT:-8082}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - MY_SECRET_DB_PASS=${MY_SECRET_DB_PASS}
      # Konfigurasi RabbitMQ (Sinkron dengan .env)
      - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}
      - SPRING_RABBITMQ_PORT=${SPRING_RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${SPRING_RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${SPRING_RABBITMQ_PASSWORD}
      - SPRING_RABBITMQ_VHOST=${SPRING_RABBITMQ_VHOST}
      - SPRING_RABBITMQ_SSL_ENABLED=${SPRING_RABBITMQ_SSL_ENABLED}
    deploy:
      resources:
        limits:
          memory: 384M
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

